analyze <- function(policy){
  analysis <- ""
  if(policy == "net_neutrality"){
    analysis <- "In the position barplot we can see that both with and without retweets the position of twitter users seems to be in favor of net neutrality and against it\\'s repeal. This opinion is held true in all 5 of the cities for the cities barplot. This is not to much surprise as a study by the Washington Post showed that 83% of voters supported net neutrality - including 75% of republicans, 89% of democrats, and 86% of independents. This explains how despite the typically different political leanings of the 5 cities they all seem to show the same ditribution of support for net neutrality. Even though Ajit Pai and the FCC decided to go against public opinion and repealed net neutrality December of 2017, you can see that net neutrality is still frequently tweeted about in the time plot. This is because people are still fighting to reinstate net neutrality and several states and companies have filed lawsuits in responce to the FCC's vote."
  }else if(policy == "gun_control"){  
    analysis <- "Gun control has been a popular subject over the past couple years as the US has experienced several mass shootings, many of which were at schools. The position plot shows support for gun control, this follows popular belief as 97% of both the general public and gun owners believed in better and consistent background checks. However, only 67% support an assault weapon ban keeping gun control in a heated debate with many still against it. You can observe this trend best in the 5 cities barplot with Omaha (typically Republican) still showing opposition, though all 5 cities still appear to favor gun control. This is probably due to the large uprising following the Parkland school shooting in Florida which is also probably why the time plot shows very active posting on the subject. It is still in question whether this will force any action from congress."
  }else if(policy == "immigration"){  
    analysis <- "The immigration ban has somewhat fallen back from the public eye which can be observed in the time plot as it is the plot taken over the longest period of time with the smallest number of tweets in each peak. This makes the data harder to interpret as it is less popular of a subject. However, you can notice that in both the overall barplot and the cities barplot the sides appear to be relatively equal, sometimes with a lean towards supporting the ban. This could be due to the fact that those who support the ban tend to be more vocal than those who don't as a recent poll from Polling Report showed that 37% would support a wall while 59% oppose. There have been several legislative movements regarding immigration but most of them are pro immigration ban, including some prototyping for a wall."
  }
  return(analysis)
}